services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass123
      MYSQL_DATABASE: piim

    volumes:
        - ./data:/var/lib/mysql
    ports:
        - 3306:3306





